### ISSUE TITLE
Embedding async

### ISSUE THREAD

**Issue by jsicherman** [PavlidisLab/Gemma-API#11]
01d77d0 internalizes async, which is a requirement for Bioconductor. However, if users want to use `gemmaAPI` with `async = T`, they still need to either use the `async` package, as:
```
async::synchronise(getGeneEvidence('XIST', async = T))
```

OR, they could use the unexported `gemmaAPI:::async` and `gemmaAPI:::synchronise`:
```
gemmaAPI:::synchronise(getGeneEvidence('XIST', async = T))
```

Using it from the `async` package would be preferable, but unusual since it's not a dependency. I'm not sure how this is usually handled since I've never seen it done before. Alternatively, the functions can be exported in `gemmaAPI` (by adding the appropriate roxygen2 tag) so they can be used normally, but this is also unusual since this isn't the `async` package...

Not sure what the best decision is, here. Maybe ask Gabor what the intended design is? Maybe he's already told you @yavyx

**Comment by yavyx** [comment]
The necessary async functions are being exported after 51d5f8f29fb397694d689b0de83ed2e9cc96b1a6, and everything is working as expected.

**Comment by jsicherman** [comment]
The question becomes: are **all** the (possibly) necessary functions exported? `async` has a number of them (https://github.com/gaborcsardi/async).

My intuition is that it is better to soft-depend on `async` instead of exporting from `aaa-async.R` and have people download it themselves if they want to use the asynchronous requests. That way, they have access to all the functions.
